version: "3.8"

#docker-compose build
#docker-compose up -d
#docker-compose down  --remove-orphans

services:

  nowports-api-ms:
    build:
      context: ${REPO_PATH}/nowports-api-ms
      dockerfile: ${REPO_PATH}/docker-infra/nowports/docker/nowports-api-ms/Dockerfile
    volumes:
      - ${REPO_PATH}/nowports-api-ms/src:/usr/src/app/src
      - ${REPO_PATH}/nowports-api-ms/.env:/usr/src/app/.env
      - ${REPO_PATH}/nowports-api-ms/package.json:/usr/src/app/package.json
      - ${REPO_PATH}/nowports-api-ms/package-lock.json:/usr/src/app/package-lock.json
    stdin_open: true
    restart: unless-stopped
    tty: true
    container_name: nowports-api-ms
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: ${REPO_PATH}/docker-infra/mysql
      dockerfile: ${REPO_PATH}/docker-infra/mysql/docker/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: toor
      MYSQL_USER: nowports
    volumes:
      - ${REPO_PATH}/docker-infra/mysql/data/var/lib/mysql:/var/lib/mysql
      - ${REPO_PATH}/docker-infra/mysql/log:/var/log/mysql/

